version: '2'

services:
  dm_for_api:  # Monitor for API microservices
    image: distributed_monitor_api
    build:
      context: ./Monitor
      dockerfile: Dockerfile
    depends_on:
      - cadvisor
    volumes:
      - ./data:/data
    network_mode: host
    restart: always
  dm_for_business:
    image: distributed_monitor_business  # Monitor for business service
    build:
      context: ./DM/DM
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:5002
    network_mode: host
    restart: always
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker:/var/lib/docker:ro"
      - "/cgroup:/cgroup:ro"
    ports:
      - 127.0.0.1:8080:8080
    privileged: true
    restart: always