version: '2'

services:
  business_microservice: #一个服务(容器)
    image: business_microservice
    build:              #构建镜像
      context: ./BusinessMicroservice  #上下文环境
      dockerfile: Dockerfile #指定的构建文件
    ports: #端口映射:服务的8080端口到本地的5001端口
      - "5001:8080"
    depends_on:
      - io_microservice
      - cpu_microservice
      - memory_microservice
    links:
      - io_microservice:io
      - cpu_microservice:cpu
      - memory_microservice:memory
    environment:
      - BV_REPORT_HOST=10.137.0.81:8080

  io_microservice:
    image: io_microservice
    build:
      context: ./IoMicroservice
      dockerfile: Dockerfile
    ports: 
      - "5003:80"

  cpu_microservice:
    image: cpu_microservice
    build:
      context: ./CpuMicroservice
      dockerfile: Dockerfile
    ports: 
      - "5004:80"

  memory_microservice:
    image: memory_microservice
    build:
      context: ./MemoryMicroservice
      dockerfile: Dockerfile
    ports: 
      - "5005:80"
    mem_limit: 512m #内存使用限制
