version: '2'
services:
  globalMonitor:
    image: global_monitor
    build:
      context: ./globalMonitor/
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment:
      MYSQL_DB: saasi
      MYSQL_HOST: mysql
      MYSQL_USERNAME: saasi
      MYSQL_PASSWORD: NewPass4!

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: saasi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: saasi
      MYSQL_PASSWORD: NewPass4!
    volumes:
      - /var/lib/mysql
      - ./globalMonitor/sql:/docker-entrypoint-initdb.d # DB Seeding 初始化数据库
  